pipeline {
    agent any

    environment {
        def myString = 'Hello World'
        def myNumber = 10
        def myBool = true
    }

    stages {
        stage('Demo') {
            steps {
                echo "myString: ${env.myString}" 
                echo "myNumber: ${env.myNumber}" 
                echo "myBool: ${env.myBool}" 
            }
        }
    }
}