pipeline {
    agent any
    stages {
        stage("Stage 1") {
            steps {
                echo "Hello from stage 1"
            }
        }
        stage("Stage 2") {
            steps {
                echo "Hello from stage 2"
            }
        }
        stage("Stage 3") {
            steps {
                echo "Hello from stage 3"
            }
        }
        stage("Final") {
            steps {
                echo "Hello from final stage"
            }
        }
    }
}