pipeline {
    agent any
    parameters {
        string(defaultValue: "", description: "Deployment Name?", name: "deploymentName")
        choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "what is AZ?", name: "azDeploy")
        booleanParam(defaultValue: false, description: "Confirm Deployment?", name: "confirmDeploy")
    }
    stages {
        stage('Deploy') {
            steps {
                echo "String set to ${params.deploymentName} \n"
                echo "choice set to ${params.azDeploy} \n"
                echo "bool set to ${params.confirmDeploy}"
            }
        }
    }
}