version: "3"
services:
  jenkins:
    build: ./
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins:/var/jenkins_home
      - apt-cacher:/var/cache/apt-cacher-ng
    stdin_open: true
    tty: true
volumes:
  jenkins:
  apt-cacher: 